name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: script/ci/cibuild

      - name: Test
        run: script/ci/test
